// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcCfzSz5MPOW63Md4YSbudrz75Ne-kYE',
    appId: '1:420352868071:web:04004c24f8c0e8d33d2c42',
    messagingSenderId: '420352868071',
    projectId: 'bioneet-a477f',
    authDomain: 'bioneet-a477f.firebaseapp.com',
    storageBucket: 'bioneet-a477f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40Sr4uzE4OYuv4uB3x2JhrooJV96UbCY',
    appId: '1:420352868071:android:c5d4d951eca9c8d13d2c42',
    messagingSenderId: '420352868071',
    projectId: 'bioneet-a477f',
    storageBucket: 'bioneet-a477f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGm0sKgSSifhp138TJ7tJUL4OuIwUKkRA',
    appId: '1:420352868071:ios:c8fac55a7526ab143d2c42',
    messagingSenderId: '420352868071',
    projectId: 'bioneet-a477f',
    storageBucket: 'bioneet-a477f.appspot.com',
    iosClientId: '420352868071-9be78e7qj8s2tdch5ipl2ojqphiun7u1.apps.googleusercontent.com',
    iosBundleId: 'com.bioneet.app.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGm0sKgSSifhp138TJ7tJUL4OuIwUKkRA',
    appId: '1:420352868071:ios:14d33f0574d7bcf13d2c42',
    messagingSenderId: '420352868071',
    projectId: 'bioneet-a477f',
    storageBucket: 'bioneet-a477f.appspot.com',
    iosClientId: '420352868071-mm3r1lg1sl7i6h15q83aj4eut8v6s2d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
